### ISSUE TITLE
nlp-기계번역 관련

### ISSUE THREAD

**Issue by ktasha45** [cpprhtn/AI-Learning-Guide#3]
|영어|준말|한글|부연 설명|
|---|---|---|---|
|recurrent neural network|RNN|순환 신경망||
|sequence-to-sequence|seq2seq|||
|attention||||
|transformer||||

이런 식으로 주제를 나눠서 하면 좋을 거 같습니다.
 - 그러면 분업도 더 쉬울 것 같습니다.

위 예시는 nlp 중에서도 기계번역과 관련된 내용입니다.

그리고 부연 설명은 위키 링크를 불러오면 되나요?

추가하려는 단어에 대한 부연 설명이 있다면 아래에 적어주세요 :)
---

**Comment by cpprhtn** [comment]
주제를 나눠서 단어를 추가하면 좀 더 기여하는 입장에서는 편할듯하네요!
좋은 의견 감사합니다!

부연은 아직은 정해진 템플릿이 없어서 자유형태긴 합니다!

직접 .md에 알파벳순으로 PR날리셔두 되고, 이슈로만 남기고 PR은 제가  올릴 수도 있습니다.
두 방법 모두 컨트리뷰터에는 올라갑니다!

기여방법 정해주셔서 코멘트 달아주세요 :)

**Comment by ktasha45** [comment]
pr을 올렸습니다!
